# Generated by Django 4.0.5 on 2023-07-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_shoppinglist_last_interation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='last_interation',
            new_name='last_interaction',
        ),
    ]
